# -*- coding: utf-8 -*-
"""PI_lab_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PiNRfJlgHhJSmW4U7BO0lNDfhfjZK-HG

Предварительно ставим всё, что надо
"""

from transformers import pipeline
import wikipedia

print('С кем хотите поговорить?')
who = input();
context = wikipedia.search(who)
print()
pipe = pipeline("question-answering", model="AlexKay/xlm-roberta-large-qa-multilingual-finedtuned-ru");
text = wikipedia.page(context[0]).content;
print(text)
while True:
  print('Ваш вопрос:')
  qu = input();
  if qu == 'конец':
      break;
  answer = pipe(question=qu, context= text)
  print(answer["answer"])

